workflows:
  build-android:
    name: Build Android APK
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
      node: 16.20.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
